### ISSUE TITLE
 Output with NA result

### ISSUE THREAD

**Issue by Tosuke-Sakagami** [josuebarrera/GenEra#28] opened 2024-11-10 04:59 UTC
Hi!
I am using GenEra ver. 1.4.2 installed by "git clone" command.
After 1st step (diamond), the result looks like proper.
**$head 84072_Diamond_results.bout
TRINITY_GG_1_c0_g1_i6.p1        TRINITY_GG_1_c0_g1_i6.p1        0.0     933     84072
TRINITY_GG_2_c0_g1_i2.p1        TRINITY_GG_2_c0_g1_i2.p1        4.37e-78        224     84072
TRINITY_GG_2_c0_g1_i2.p1        TRINITY_GG_1204_c0_g1_i1.p1     9.33e-07        43.5    84072
TRINITY_GG_3_c1_g1_i3.p1        TRINITY_GG_3_c1_g1_i3.p1        2.39e-73        213     84072
TRINITY_GG_3_c1_g1_i3.p1        TRINITY_GG_1038_c530_g1_i8.p2   4.88e-68        199     84072
TRINITY_GG_3_c1_g1_i3.p1        TRINITY_GG_1038_c530_g2_i1.p1   3.99e-52        169     84072
TRINITY_GG_7_c0_g1_i3.p1        TRINITY_GG_7_c0_g1_i3.p1        2.37e-145       402     84072
TRINITY_GG_7_c1_g1_i5.p1        TRINITY_GG_7_c1_g1_i5.p1        1.35e-177       487     84072
TRINITY_GG_8_c0_g1_i17.p1       TRINITY_GG_8_c0_g1_i17.p1       0.0     1383    84072
TRINITY_GG_8_c0_g1_i17.p1       TRINITY_GG_8_c0_g1_i5.p2        0.0     1383    84072
$tail 84072_Diamond_results.bout
TRINITY_GG_2787_c0_g1_i2.p1     XP_045873036.1  8.86e-06        61.2    9662
TRINITY_GG_2787_c0_g1_i2.p1     CAF0710714.1    8.89e-06        61.2    104777
TRINITY_GG_2787_c0_g1_i2.p1     KAH8252699.1    8.92e-06        61.2    46829
TRINITY_GG_2787_c0_g1_i2.p1     CAH8445850.1    8.96e-06        61.2    31246
TRINITY_GG_2787_c0_g1_i2.p1     XP_027227819.1  9.00e-06        61.2    6689
TRINITY_GG_2787_c0_g1_i2.p1     XP_056894628.1  9.23e-06        60.5    433684
TRINITY_GG_2787_c0_g1_i2.p1     CAD8085739.1    9.23e-06        61.2    5886
TRINITY_GG_2787_c0_g1_i2.p1     KAI2658918.1    9.74e-06        60.8    84645
TRINITY_GG_2787_c0_g1_i2.p1     XP_052832602.1  9.76e-06        60.8    37653
TRINITY_GG_2787_c0_g1_i2.p1     VVC38282.1      9.91e-06        60.8    506608**

Then, I rerun with the following command after fixation of some error (changed no. of threads)
`genEra -q longest_orfs.pep  -t 84072 -b /diamond_db/genera/nr  -d /diamond_db/genera/taxdump -i true -p /genEra/test/tmp_84072_21145/84072_Diamond_results.bout`
Finally, I got the following message.
**Step 3 finished!
The age assignment for your individual genes can be found in /genEra/test2/84072_gene_ages.tsv
The deepest traceable homologs for each of your genes can be found in /genEra/test2/84072_deepest_homolog.tsv
The possible ages for the genes with a taxonomic representativeness below 30 percent can be found in /genEra/test2/84072_ambiguous_phylostrata.tsv
The estimation of gene family founder events can be found in /genEra/test2/84072_founder_events.tsv
The number of individual genes that could be assigned to each phylostratum are summarized in /genEra/test2/84072_gene_age_summary.tsv
The number of of gene family founder events per phylostratum are summarized in /genEra/test2/84072_founder_summary.tsv
genEra finished at:
Sat Nov  9 11:36:13 PM CST 2024
Enjoy your results!!!**

But, there no result in those files. For example, this is 84072_Diamond_results.bout, but everything is NA.
**#gene   phylostratum    rank    taxonomic_representativeness
TRINITY_GG_1008_c4_g1_i22.p1    Absent from the DIAMOND/MMseqs2 results NA      NA
TRINITY_GG_1015_c0_g1_i4.p1     Absent from the DIAMOND/MMseqs2 results NA      NA
TRINITY_GG_1015_c0_g1_i4.p2     Absent from the DIAMOND/MMseqs2 results NA      NA
TRINITY_GG_1015_c1_g1_i1.p1     Absent from the DIAMOND/MMseqs2 results NA      NA**

I saw the following message during (probably) 3rd step. There were the same massage for all of the genes (proteins).
**rm: cannot remove '/genEra/test2/tmp_84072_20040/tmp_TRINITY_GG_1658_c1191_g1_i3.p1.bout': No such file or directory
awk: fatal: cannot open file `/genEra/test2/tmp_84072_20040/tmp_TRINITY_GG_1658_c1191_g1_i3.p2.bout' for reading: No such file or directory**

So, what should I do to fix this? I appreciate your help. 
Sincerely, 
Haruki

**Comment by josuebarrera** [comment] 2024-11-10 16:11
Dear Haruki,

Thank you for your interest in using `GenEra` and for the detailed explanation of your issue!
As you mention, the first step of the pipeline ran smoothly, so you can safely use the `84072_Diamond_results.bout` file. Which means that the error happened either on the second or third step of the pipeline. I'll have to ask you for a bit of extra information that will help me identify the issue:
- Could you please share with me the STDOUT or log file for the `GenEra` run? Maybe there is an important error message before step 3 that can help us solve the issue quickly.
- Could you also please share with me the first few lines of the `84072_ncbi_lineages*` file to see if it was properly written by `GenEra`?

My suspicion is that the error is associated with the script [FASTSTEP3R](https://github.com/josuebarrera/GenEra/blob/main/FASTSTEP3R), which splits  `84072_Diamond_results.bout` into smaller chunks to speed up the analysis (GenEra is not finding the chunk files for some reason).

Could you please run the same command that you showed me, but adding `-F false` at the end? It will run slower, but I suspect this will at least give you a complete output file for you to work with while I figure out the error and solve it.

Best regards,
Josué

**Comment by Tosuke-Sakagami** [comment] 2024-11-11 03:09
Thank you for your quick reply , Dr. Josué.

Finally, I succeeded with `-F false` command. 
Although there is no log file, here is  the first few lines of `84072_ncbi_lineages.csv` file

**$head 84072_ncbi_lineages.csv
tax_id,species,clade2,clade1,kingdom,clade,superkingdom,no rank
1,,,,,,,root
2,,,,,,Bacteria,cellular organisms
6,,,,,,Bacteria,cellular organisms
7,Azorhizobium caulinodans,,,,,Bacteria,cellular organisms
9,Buchnera aphidicola,,,,,Bacteria,cellular organisms
10,,,,,,Bacteria,cellular organisms
11,Cellulomonas gilvus,,,Bacillati,,Bacteria,cellular organisms
13,,,,,,Bacteria,cellular organisms
14,Dictyoglomus thermophilum,,,,,Bacteria,cellular organisms**

And, I have two more question.
1. Step3 was using full threads as shown the following. If I use `-n`, can I decrease no. of threads for this? (Default require 20 threads) 
**STARTING STEP 3: ASSIGNING AGES TO YOUR QUERY GENES WITH Erassignment
Running Erassignment using 256 threads**

2. For the downstream analysis, `myTAI` require `ExpressionMatrix` for transcriptome analysis. My data are RNA-seq data under different conditions. `GenEra` requires protein seq. but `myTAI` does gene expression. So, the name of seq. is not pairwise now (e.g., gene id:TRINITY_GG_1038_c1049_g1, protein id: TRINITY_GG_1038_c1049_g1_i10.p1, TRINITY_GG_1038_c1049_g1_i10.p2 etc.). If I change protein ids to gene ids, I need choose `Phylostratum` for each gene. Do you have any suggestion? Or, Am I misunderstanding?

Best regards,
Haruki

**Comment by josuebarrera** [comment] 2024-11-11 12:03
Dear Haruki,

I'm glad you managed to obtain the gene ages for your organism! Your `ncbi_lineages.csv` file looks normal, so the problem is clearly in step 3, specifically using "fast mode" with `FASTSTEP3R`. I suspect it has something to do with the complex gene names given automatically by Trinity. We'll look into it and keep you posted!

Regarding your questions:

1. By default, `GenEra` uses all the available threads in your machine. You can use `-n` to specify how many threads you'd like to use for your analysis (e.g., if you'd like to use only 10 threads, you can include `-n 10` in your command).
2. If I understand your question correctly, the problem is that you have more than one gene age per locus due to alternative splicing (_i.e._, different proteins encoded in the same gene have different ages). If that is the case, I would suggest you use the oldest assigned age from all the isoforms for any given gene (_e.g._, if `TRINITY_GG_1038_c1049_g1_i10.p1` has a relative age `1` and `TRINITY_GG_1038_c1049_g1_i10.p2` has a relative age `3`, I would assign `TRINITY_GG_1038_c1049_g1` with gene age `1`). This is because shorter isoforms can miss conserved domains that help DIAMOND find distantly related homologs for that gene.

I hope this helps. Enjoy your results!
Cheers,
Josué

**Comment by josuebarrera** [comment] 2024-11-11 12:47
Dear Haruki,

Please let me know if you have any further inquiries. I'll close the issue thread for now.

Cheers,
Josué

**Closed by josuebarrera** 2024-11-11 12:47 UTC
Labels: bug
